/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx,ts,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        // ── Stitch Material Design 3 Palette ──────────────────────────────────
        'on-secondary-container': '#572000',
        'tertiary-container': '#007650',
        'surface-container-lowest': '#ffffff',
        'on-primary-fixed-variant': '#5a00c6',
        'on-primary-fixed': '#25005a',
        'on-tertiary-fixed-variant': '#005236',
        'on-background': '#111c2d',
        background: '#f9f9ff',
        'inverse-on-surface': '#ecf1ff',
        'secondary-fixed': '#ffdbcc',
        'inverse-surface': '#263143',
        'surface-container-high': '#dee8ff',
        'on-secondary': '#ffffff',
        'inverse-primary': '#d2bbff',
        'surface-container-low': '#f0f3ff',
        'on-secondary-fixed': '#351000',
        surface: '#f9f9ff',
        'surface-variant': '#d8e3fb',
        'on-secondary-fixed-variant': '#7a3000',
        error: '#ba1a1a',
        'surface-dim': '#cfdaf2',
        'surface-container-highest': '#d8e3fb',
        secondary: '#a04100',
        'primary-fixed': '#eaddff',
        'on-tertiary-fixed': '#002113',
        'on-tertiary': '#ffffff',
        'on-error-container': '#93000a',
        'on-surface-variant': '#4a4455',
        'on-error': '#ffffff',
        'surface-bright': '#f9f9ff',
        'tertiary-fixed': '#6ffbbe',
        'on-primary-container': '#ede0ff',
        'on-surface': '#111c2d',
        'outline-variant': '#ccc3d8',
        tertiary: '#005b3d',
        outline: '#7b7487',
        'on-primary': '#ffffff',
        'surface-tint': '#732ee4',
        'primary-fixed-dim': '#d2bbff',
        'surface-container': '#e7eeff',
        'error-container': '#ffdad6',
        primary: '#630ed4',
        'secondary-container': '#fe6b00',
        'secondary-fixed-dim': '#ffb693',
        'primary-container': '#7c3aed',
        'on-tertiary-container': '#76ffc2',
        'tertiary-fixed-dim': '#4edea3',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        '2xl': '1rem',
        '3xl': '1.5rem',
        full: '9999px',
      },
      spacing: {
        'inner-padding': '24px',
        'card-gap': '24px',
        'container-padding': '32px',
        base: '8px',
        'sidebar-width': '260px',
      },
      fontFamily: {
        headline: ['Outfit', 'sans-serif'],
        body: ['Inter', 'system-ui', 'sans-serif'],
        label: ['Inter', 'system-ui', 'sans-serif'],
      },
      fontSize: {
        'label-sm': ['12px', { lineHeight: '1.2', fontWeight: '600' }],
        'label-md': [
          '14px',
          { lineHeight: '1.4', fontWeight: '500', letterSpacing: '0.01em' },
        ],
        'body-md': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        'headline-md': ['20px', { lineHeight: '1.4', fontWeight: '600' }],
        'headline-lg': [
          '32px',
          { lineHeight: '1.3', fontWeight: '600', letterSpacing: '-0.01em' },
        ],
        display: [
          '40px',
          { lineHeight: '1.2', fontWeight: '700', letterSpacing: '-0.02em' },
        ],
      },
      animation: {
        'spin-slow': 'spin 1.5s linear infinite',
      },
    },
  },
  plugins: [],
};
