/**
 * themes.js — React Native Theme System
 */

export const THEMES = [
  {
    id: 'dark',
    name: 'Default Dark',
    emoji: '🌑',
    unlockLevel: 0,
    description: 'The classic MicroMind dark experience',
    colors: {
      bgMain: '#0f172a',
      bgSidebar: '#1e293b',
      bgHeader: 'rgba(30, 41, 59, 0.95)',
      bgCard: '#1e293b',
      bgCardGlass: 'rgba(30, 41, 59, 0.75)',
      textPrimary: '#f8fafc',
      textSecondary: '#94a3b8',
      borderColor: '#334155',
      primaryViolet: '#a855f7',
      primaryVioletHover: '#9333ea',
      accentGradient: ['#8b5cf6', '#6366f1'],
      isDark: true,
    },
  },
  {
    id: 'light',
    name: 'Default Light',
    emoji: '☀️',
    unlockLevel: 0,
    description: 'Clean and bright workspace',
    colors: {
      bgMain: '#f4f6fc',
      bgSidebar: '#ffffff',
      bgHeader: 'rgba(255, 255, 255, 0.95)',
      bgCard: '#ffffff',
      bgCardGlass: 'rgba(255, 255, 255, 0.85)',
      textPrimary: '#1e293b',
      textSecondary: '#64748b',
      borderColor: '#e2e8f0',
      primaryViolet: '#7c3aed',
      primaryVioletHover: '#6d28d9',
      accentGradient: ['#7c3aed', '#4f46e5'],
      isDark: false,
    },
  },
  {
    id: 'cyberpunk',
    name: 'Cyberpunk Neon',
    emoji: '⚡',
    unlockLevel: 5,
    description: 'Electric neon vibes from the future',
    colors: {
      bgMain: '#060612',
      bgSidebar: '#0b0b1f',
      bgHeader: 'rgba(11, 11, 31, 0.95)',
      bgCard: '#0b0b1f',
      bgCardGlass: 'rgba(11, 11, 31, 0.85)',
      textPrimary: '#e0f7fa',
      textSecondary: '#80cdd8',
      borderColor: 'rgba(0, 245, 255, 0.3)',
      primaryViolet: '#00f5ff',
      primaryVioletHover: '#00c8d4',
      accentGradient: ['#00f5ff', '#bf00ff'],
      isDark: true,
    },
  },
  {
    id: 'sunset',
    name: 'Sunset Pastel',
    emoji: '🌅',
    unlockLevel: 10,
    description: 'Warm pastels and golden-hour tones',
    colors: {
      bgMain: '#fdf4f0',
      bgSidebar: '#fff8f5',
      bgHeader: 'rgba(255, 248, 245, 0.95)',
      bgCard: '#fff8f5',
      bgCardGlass: 'rgba(255, 248, 245, 0.85)',
      textPrimary: '#3d1a1a',
      textSecondary: '#7a4040',
      borderColor: 'rgba(224, 90, 106, 0.3)',
      primaryViolet: '#e05a6a',
      primaryVioletHover: '#c94458',
      accentGradient: ['#f97316', '#e05a6a'],
      isDark: false,
    },
  },
  {
    id: 'deepspace',
    name: 'Deep Space Navy',
    emoji: '🚀',
    unlockLevel: 15,
    description: 'Vast cosmos of midnight navy and stars',
    colors: {
      bgMain: '#020814',
      bgSidebar: '#05101e',
      bgHeader: 'rgba(5, 16, 30, 0.95)',
      bgCard: '#05101e',
      bgCardGlass: 'rgba(5, 16, 30, 0.85)',
      textPrimary: '#e2eeff',
      textSecondary: '#7d9dc7',
      borderColor: 'rgba(96, 165, 250, 0.3)',
      primaryViolet: '#60a5fa',
      primaryVioletHover: '#3b82f6',
      accentGradient: ['#1e40af', '#60a5fa'],
      isDark: true,
    },
  },
];

export const DEFAULT_THEME = THEMES[0];
